name: My Docker Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: |
          sudo apt-get update
      - name: Install Docker
        run: |
          sudo apt-get install -y docker.io
      - name: Verify Docker installation
        run: docker version
      - name: Build and push Docker image
        run: |
          docker run hello-world:latest