name: My Next.js Workflow

on: [push]

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code from Github
      - run: npm install
        name: Install npm packages
      - run: node app.js
        name: Run node application
      - name: Build project assets
        run: npm run build
