name: My Mac Workflow

on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get upgrade -y
      - run: sudo apt install nodejs npm
      - run: npm --version
      - run: node --version
      - run: node app.js
