name: Node.js and NPM installation

on: [push]

jobs:
  install:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install NPM packages
      run: npm install